import Providers from '@/components/Providers';
import type { Metadata } from 'next';

import LoadingProgress from '@/components/ui/loading/LoadingProgress';
import { Suspense } from 'react';
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import 'react-loading-skeleton/dist/skeleton.css';

export const metadata: Metadata = {
    title: 'AnimeVS Welcome',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <div id="content">
                    <Providers>
                        <Suspense fallback={<LoadingProgress />}>{children}</Suspense>
                    </Providers>
                </div>
            </body>
        </html>
    );
}
